### PR TITLE
OOP school library: add Person, Student and Teacher classes

### PR DESCRIPTION
**Pull request by katfogy**
**In this PR we:**

- [ ] Used Gitflow/GithubFlow properly
- [ ] Used Linters with no errors
- [ ] Created the Person class
- [ ] Created the Student class that inherits the Person class
- [ ] Created the Teacher class that inherits the Person class
- [ ] Classes are in separate files
- [ ] I used Public and private for Method Exposure

### CODE REVIEW

**Review by Gambit142 — APPROVED** [review]
Hi @katfogy 👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights
- All linter checks passed ✔️ 
- Created `Person` class ✔️ 
- Created `Teacher` Class ✔️ 
- Created `Student` class ✔️ 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by katfogy** [comment]
Thank you @Gambit142  for your thorough Review

**Comment by katfogy** [comment]
Thank you @Gambit142  for your thorough Review

**Comment by Gambit142** [comment]
@katfogy, you are welcome

**Pull request merged**
